### ISSUE TITLE
🐛 Footer area does not stick to the bottom of the user's website.

### ISSUE THREAD

**Issue by iflinda** [Runik-3/runik-app#100]
![image](https://user-images.githubusercontent.com/68607795/143999845-a2e010b9-3294-4985-96d6-ceb9def61367.png)

Footer area is currently not set to stick to the bottom of the screen.

**Comment by EliasMatteo** [comment]
I added positioning for the footer for the details page of absolute bottom-0 this fixed the issue and it now stays on bottom
