### ISSUE TITLE
✨No exit button or click off window event to handle closing the installation modal.

### ISSUE THREAD

**Issue by iflinda** [Runik-3/runik-app#64]
![image](https://user-images.githubusercontent.com/68607795/143199354-5e3fc8d9-654b-4260-9a48-cb10845df440.png)
![image](https://user-images.githubusercontent.com/68607795/143199488-389eb8e3-f0f9-4e5b-8cdd-1f409695bc32.png)

When downloading a dictionary, there is no way to cancel the process from the window.

**Comment by matteomiceli** [comment]
handled this... should be live on dev and install flow
