### ISSUE TITLE
🐛 Button on the left side of the navigation bar has no hover effect.

### ISSUE THREAD

**Issue by iflinda** [Runik-3/runik-app#67]
Fix the image link on all the left icons on the navigation bar component. They currently do not produce an on hover effect to let users know that it is a clickable element.

**Comment by EliasMatteo** [comment]
I added `hover:opacity-60 cursor-pointer transition-ease-in-out duration-500` to both the library icon and its open icon also the search bar button icon to indicate they are clickable components
